[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  mikalhart/TinyGPSPlus@^1.1.0
  paulstoffregen/AltSoftSerial@^1.4
