[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  adafruit/Adafruit SHT4x Library@^1.0.5
  https://github.com/adafruit/Adafruit_TCS3448.git#1.0.0
  milesburton/DallasTemperature@^4.0.4
  bblanchon/ArduinoJson@^6.21.5
  adafruit/RTClib@^2.1.4

build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
