[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  adafruit/Adafruit SHT4x Library@^1.0.5
  https://github.com/adafruit/Adafruit_TCS3448.git#1.0.0
  milesburton/DallasTemperature@^4.0.4
  adafruit/RTClib@^2.1.4
  mikalhart/TinyGPSPlus@^1.1.0
  paulstoffregen/AltSoftSerial@^1.4
