[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  milesburton/DallasTemperature@^4.0.4
  paulstoffregen/OneWire@^2.3.8
